openapi: 3.0.1
info:
  title: Flight Booking System
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /api/v1/flights:
    get:
      summary: Получить список рейсов
      tags:
        - Gateway API
      security:
        - bearerAuth: [ ]
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: number
            minimum: 0
        - name: size
          in: query
          required: false
          schema:
            type: number
            minimum: 1
            maximum: 100
      responses:
        "200":
          description: Список рейсов
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginationResponse"
        "401":
          description: Ошибка авторизации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/tickets:
    get:
      summary: Информация по всем билетам пользователя
      tags:
        - Gateway API
      security:
        - bearerAuth: [ ]
      responses:
        "200":
          description: Информация по всем билетам
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TicketResponse"
        "401":
          description: Ошибка авторизации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    post:
      summary: Покупка билета
      tags:
        - Gateway API
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TicketPurchaseRequest"
      responses:
        "200":
          description: Информация о купленном билете
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TicketPurchaseResponse"
        "400":
          description: Ошибка валидации данных
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationErrorResponse"
        "401":
          description: Ошибка авторизации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  "/api/v1/tickets/{ticketUid}":
    get:
      summary: Информация по конкретному билету
      tags:
        - Gateway API
      security:
        - bearerAuth: [ ]
      parameters:
        - name: ticketUid
          schema:
            type: string
            format: uuid
          in: path
          description: UUID билета
          required: true
      responses:
        "200":
          description: Информация по конкретному билету
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TicketResponse"
        "401":
          description: Ошибка авторизации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Билет не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    delete:
      summary: Возврат билета
      tags:
        - Gateway API
      security:
        - bearerAuth: [ ]
      parameters:
        - name: ticketUid
          schema:
            type: string
            format: uuid
          in: path
          description: UUID билета
          required: true
      responses:
        "204":
          description: Возврат билета успешно выполнен
        "401":
          description: Ошибка авторизации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Билет не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/me:
    get:
      summary: Информация о пользователе
      tags:
        - Gateway API
      security:
        - bearerAuth: [ ]
      responses:
        "200":
          description: Полная информация о пользователе
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfoResponse"
        "401":
          description: Ошибка авторизации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/privilege:
    get:
      summary: Получить информацию о состоянии бонусного счета
      tags:
        - Gateway API
      security:
        - bearerAuth: [ ]
      responses:
        "200":
          description: Данные о бонусном счете
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PrivilegeInfoResponse"
        "401":
          description: Ошибка авторизации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    PaginationResponse:
      type: object
      example:
        {
          "page": 1,
          "pageSize": 1,
          "totalElements": 1,
          "items": [
            {
              "flightNumber": "AFL031",
              "fromAirport": "Санкт-Петербург Пулково",
              "toAirport": "Москва Шереметьево",
              "date": "2021-10-08 20:00",
              "price": 1500
            }
          ]
        }
      properties:
        page:
          type: number
          description: Номер страницы
        pageSize:
          type: number
          description: Количество элементов на странице
        totalElements:
          type: number
          description: Общее количество элементов
        items:
          type: array
          items:
            $ref: "#/components/schemas/FlightResponse"

    FlightResponse:
      type: object
      example:
        {
          "flightNumber": "AFL031",
          "fromAirport": "Санкт-Петербург Пулково",
          "toAirport": "Москва Шереметьево",
          "date": "2021-10-08 20:00",
          "price": 1500
        }
      properties:
        flightNumber:
          type: string
          description: Номер полета
        fromAirport:
          type: string
          description: Страна и аэропорт прибытия
        toAirport:
          type: string
          description: Страна и аэропорт прибытия
        date:
          type: string
          description: Дата и время вылета
          format: ISO 8601
        price:
          type: number
          description: Стоимость

    TicketResponse:
      type: object
      example:
        {
          "ticketUid": "049161bb-badd-4fa8-9d90-87c9a82b0668",
          "flightNumber": "AFL031",
          "fromAirport": "Санкт-Петербург Пулково",
          "toAirport": "Москва Шереметьево",
          "date": "2021-10-08 20:00",
          "price": 1500,
          "status": "PAID"
        }
      properties:
        ticketUid:
          type: string
          description: UUID билета
          format: uuid
        flightNumber:
          type: string
          description: Номер полета
        fromAirport:
          type: string
          description: Страна и аэропорт прибытия
        toAirport:
          type: string
          description: Страна и аэропорт прибытия
        date:
          type: string
          description: Дата и время вылета
          format: ISO 8601
        price:
          type: number
          description: Стоимость
        status:
          type: string
          description: Статус билета
          enum:
            - PAID
            - CANCELED

    UserInfoResponse:
      type: object
      example:
        {
          "tickets": [
            {
              "ticketUid": "049161bb-badd-4fa8-9d90-87c9a82b0668",
              "flightNumber": "AFL031",
              "fromAirport": "Санкт-Петербург Пулково",
              "toAirport": "Москва Шереметьево",
              "date": "2021-10-08 20:00",
              "price": 1500,
              "status": "PAID"
            }
          ],
          "privilege": {
            "balance": 1500,
            "status": "GOLD"
          }
        }
      properties:
        tickets:
          type: array
          description: Информация о билетах пользоватлея
          items:
            $ref: "#/components/schemas/TicketResponse"
        privilege:
          $ref: "#/components/schemas/PrivilegeShortInfo"

    PrivilegeShortInfo:
      type: object
      properties:
        balance:
          type: string
          description: Баланс бонусного счета
        status:
          type: string
          description: Статус в бонусной программе
          enum:
            - BRONZE
            - SILVER
            - GOLD

    PrivilegeInfoResponse:
      type: object
      example:
        {
          "balance": 1500,
          "status": "GOLD",
          "history": [
            {
              "date": "2021-10-08T19:59:19Z",
              "ticketUid": "049161bb-badd-4fa8-9d90-87c9a82b0668",
              "balanceDiff": 1500,
              "operationType": "FILL_IN_BALANCE"
            }
          ]
        }
      properties:
        balance:
          type: string
          description: Баланс бонусного счета
        status:
          type: string
          description: Статус в бонусной программе
          enum:
            - BRONZE
            - SILVER
            - GOLD
        history:
          type: array
          description: История изменения баланса
          items:
            $ref: "#/components/schemas/BalanceHistory"

    BalanceHistory:
      type: object
      example:
        {
          "date": "2021-10-08T19:59:19Z",
          "ticketUid": "049161bb-badd-4fa8-9d90-87c9a82b0668",
          "balanceDiff": 1500,
          "operationType": "FILL_IN_BALANCE"
        }
      properties:
        date:
          type: string
          description: Дата и время операции
          format: ISO 8601
        balanceDiff:
          type: string
          description: Изменение баланса
        ticketUid:
          type: string
          description: UUID билета по которому была операция с бонусами
        operationType:
          type: string
          description: Тип операции
          enum:
            - FILL_IN_BALANCE
            - DEBIT_THE_ACCOUNT
            - FILLED_BY_MONEY

    TicketPurchaseRequest:
      type: object
      example:
        {
          "flightNumber": "AFL031",
          "price": 1500,
          "paidFromBalance": true
        }
      properties:
        flightNumber:
          type: string
          description: Номер полета
        price:
          type: number
          description: Стоимость
        paidFromBalance:
          type: boolean
          description: Выполнить списание бонусных баллов в учет покупки билета

    TicketPurchaseResponse:
      type: object
      example:
        {
          "ticketUid": "049161bb-badd-4fa8-9d90-87c9a82b0668",
          "flightNumber": "AFL031",
          "fromAirport": "Санкт-Петербург Пулково",
          "toAirport": "Москва Шереметьево",
          "date": "2021-10-08 20:00",
          "price": 1500,
          "paidByMoney": 1500,
          "paidByBonuses": 0,
          "status": "PAID",
          "privilege": {
            "balance": 1500,
            "status": "GOLD"
          }
        }
      properties:
        ticketUid:
          type: string
          description: UUID билета
          format: uuid
        flightNumber:
          type: string
          description: Номер полета
        fromAirport:
          type: string
          description: Страна и аэропорт прибытия
        toAirport:
          type: string
          description: Страна и аэропорт прибытия
        date:
          type: string
          description: Время вылета
          format: ISO 8601
        status:
          type: string
          description: Статус билета
          enum:
            - PAID
            - CANCELED
        price:
          type: number
          description: Стоимость
        paidByMoney:
          type: number
          description: Сумма оплаченная деньгами
        paidByBonuses:
          type: number
          description: Сумма оплаченная бонусами
        privilege:
          $ref: "#/components/schemas/PrivilegeShortInfo"

    ErrorDescription:
      type: object
      properties:
        field:
          type: string
        error:
          type: string

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Информация об ошибке

    ValidationErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Информация об ошибке
        errors:
          type: array
          description: Массив полей с описанием ошибки
          items:
            $ref: "#/components/schemas/ErrorDescription"
